image: maven:3.8.6-eclipse-temurin-17-jdk

services:
  - name: mysql:5.7
    alias: db

variables:
  MYSQL_DATABASE: root
  MYSQL_ROOT_PASSWORD: P@M1dobken
  MYSQL_USER: root
  MYSQL_PASSWORD: P@M1dobken

stages:
  - build
  - test

say-hello:
  stage: build
  script:
    - mvn clean package -DskipTests -batch-mode -U
  artifacts:
    paths:
      - target/*.jar
  
test_job:
  stage: test
  script:
    - mvn test jacoco:report
  artifacts:
    paths:
      - target/site/jacoco/
      - target/surefire-reports/
      