image: maven:3.8.6-eclipse-temurin-17-jdk
stages:
  - build
  - test

say-hello:
  stage: build
  script:
    - mvn clean package -DskipTests -batch -mode -U
  artifacts:
    paths:
      - target/*jar
  
test-job:
  stage: test
  script:
    - mvn test jacoco:report
  artifacts:
    paths:
      - target/jacoco.exec
