# application.yml
spring:
    application:
        name: narrarive
    datasource:
        url: jdbc:mysql://localhost:3306/localhost:3306/narrative_management?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
        username: root
        password: P@M1dobken
        hikari:
            maximum-pool-size: 10
            minimum-idle: 2
            idle-timeout: 30000
            connection-timeout: 30000
            max-lifetime: 1800000
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true